export default {
  ALGORITHM_PANEL: {
    DRAG_NODE: 'DRAG_NODE',
    DROP_NODE: 'DROP_NODE',
    SELECT_NODE: 'SELECT_NODE',
    ABANDON_NODE: 'ABANDON_NODE',
  },
  NODES: {
    CREATE_NODE: 'CREATE_NODE',
    CHANGE_NODE: 'CHANGE_NODE',
    REMOVE_NODE: 'REMOVE_NODE',
  },
  MESSAGES: {
    CREATE_MESSAGE: 'CREATE_MESSAGE',
  },
  GAME: {
    STARTED: 'GAME_STARTED',
    ROUND_STARTED: 'ROUND_STARTED',
    ROUND_FINISHED: 'ROUND_FINISHED',
    FINISHED: 'GAME_FINISHED',
  },
};
