const ACTIONS = {
  ALGORITHM_PANEL: {
    DRAG_NODE: 'DRAG_NODE',
    DROP_NODE: 'DROP_NODE',
    SELECT_NODE: 'SELECT_NODE',
    ABANDON_NODE: 'ABANDON_NODE',
    MISTAKE: 'MISTAKE',
    SET_STATE: 'GAME_SET_STATE'
  },
  NODES: {
    CREATE: 'NODE_CREATE',
    CHANGE: 'NODE_CHANGE',
    REMOVE: 'NODE_REMOVE'
  },
  LINKS: {
    CREATE: 'LINK_CREATE',
    REMOVE: 'LINK_REMOVE',
    CHANGE: 'LINK_CHANGE'
  },
  MESSAGES: {
    CREATE_MESSAGE: 'CREATE_MESSAGE'
  },
  GAME: {
    STARTED: 'GAME_STARTED',
    ROUND_STARTED: 'ROUND_STARTED',
    ROUND_FINISHED: 'ROUND_FINISHED',
    FINISHED: 'GAME_FINISHED'
  },
  MENU: {
    SAVE: 'MENU_SAVE',
    LOAD: 'MENU_LOAD'
  }
}

export default ACTIONS
